### ISSUE TITLE
Response history

### ISSUE THREAD

**Issue by machinexa2** [sonic182/aiosonic#176]
**Is your feature request related to a problem? Please describe.**
Requests has a nice `response.history` feature which gives me each response text, headers and cookies, however, this module doesn't have one. It has only response_initial which doesn't let me see response cookie (should be derived from set-cookie header but not necessary) nor response headers (more necessary than response header). Like when i do same thing on requests it gives me this header
```
{'Server': 'nginx', 'Date': 'Sun, 08 Nov 2020 11:51:40 GMT', 'Content-Type': 'text/html', 'Content-Length': '162', 'Location': 'https://www.redacted.com/newsticker/#', 'Set-Cookie': 'hello=world', 'Last-Modified': 'Sun, 08 Nov 2020 11:51:40 GMT', 'Cache-Control': 'private', 'Age': '0', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Connection': 'keep-alive'}
```
while response_initial gives me only this
```
{'version': '1.1', 'code': '301', 'reason': 'Moved'}
```
**Describe the solution you'd like**
I want response headers to be fully displayed, like requests 

**Describe alternatives you've considered**
Idk 

**Additional context**

**Comment by machinexa2** [comment]
I dont want all history but at least 1st 302 and last 200 response headers should be there

**Comment by machinexa2** [comment]
Even aiohttp has this feature:
```
(<ClientResponse(http://www.redacted.de/newsticker/%23%0D%0Ahello:world) [301 Moved Permanently]>
<CIMultiDictProxy('Server': 'nginx', 'Date': 'Mon, 09 Nov 2020 02:17:18 GMT', 'Content-Type': 'text/html', 'Content-Length': '162', 'Location': 'https://www.redacted.com/newsticker/#', 'hello': 'world', 'Last-Modified': 'Mon, 09 Nov 2020 02:17:18 GMT', 'Cache-Control': 'private', 'Age': '0', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Connection': 'keep-alive')>
,)
(<ClientResponse(https://www.redacted.com/lp/%0Ahello:world) [301 Moved Permanently]>
<CIMultiDictProxy('Date': 'Mon, 09 Nov 2020 02:17:25 GMT', 'Content-Type': 'text/html', 'Content-Length': '162', 'Connection': 'keep-alive', 'x-gi': 'NP', 'location': 'https://www.redacted.com/lp/redirects/?olp=/lp/', 'hello': 'world')>
,)

```

**Comment by machinexa2** [comment]
The code is somewhat faulty 
```
res_data = None
            res_data = await connection.reader.readline()
            print(res_data)
            if b': ' not in res_data:
            response._set_header(*HttpHeaders._clear_line(res_data))
```
if i print res_data i get headers in both response but after that its lost
```
b'Server: nginx\r\n'
b'Date: Mon, 09 Nov 2020 03:35:29 GMT\r\n'
b'Content-Type: text/html\r\n'
b'Content-Length: 162\r\n'
b'Location: https://www.redacted.com/newsticker/\r\n'
b'hello:world\r\n'
<class 'aiosonic.HttpHeaders'>
b'Date: Mon, 09 Nov 2020 03:35:34 GMT\r\n'
b'Content-Type: text/html\r\n'
b'Content-Length: 162\r\n'
b'Connection: keep-alive\r\n'
b'x-gi: NP\r\n'
b'location: https://www.redacted.com/lp/redirects/?olp=/lp/\r\n'
b'hello: world\r\n'
b'\r\n'
<class 'aiosonic.HttpHeaders'>
```

**Comment by machinexa2** [comment]
@sonic182

**Comment by machinexa2** [comment]
Nice you merged lot of pull requests. Good. I will see if there's any additional problems or not. Anyways your work is awesome. Keep it up.

**Comment by machinexa2** [comment]
@sonic182 Though this is not a issue, but a small question, would you show how to fetch like lots of urls in README.md,
like with aiohttp i would do something as 
```py
async def get(url):
    async with aiohttp.ClientSession(timeout=timeout) as session:
        try:
            async with session.get(url) as response:
                actual_headers = response.headers
                return url, actual_headers
        except (InvalidURL,TimeoutError,ClientConnectorError,ClientResponseError):
            return None
        except Exception as E:
            print(E,E.__class__)
            return None

loop = asyncio.get_event_loop()
coroutines = (get(_) for _ in urls)
results = loop.run_until_complete(asyncio.gather(*coroutines))
print(results)
```
So, if you update readme.md it would be nice

**Comment by machinexa2** [comment]
Note that the problem about response history headers has been fixed and this issue can be successfully closed.

**Comment by sonic182** [comment]
I added some more documentation.

For the global timeout, the client accepts a TCPConnector class, and this accepts global timeouts -> https://aiosonic.readthedocs.io/en/latest/reference.html#client

Concurrente example -> https://aiosonic.readthedocs.io/en/latest/examples.html#concurrent-requests

I maybe do the history so I'll keep the issue opened. The Jar of cookies is a TODO in the readme (Sessions with Cookie Persistence) that I'll do whenever I got time and desire 😄

**Comment by sonic182** [comment]
Cookies JAR in https://github.com/sonic182/aiosonic/pull/190

Gonna skip response history, to keep package minimal, and it can be easily implementer for whoever need's it easily by overriding/creating a child class from HTTPClient
