### ISSUE TITLE
Post request returns unsupported media type

### ISSUE THREAD

**Issue by rei-sys** [sonic182/aiosonic#226]
**Describe the bug**
Using aiosonic I get a 415 status code.

**To Reproduce**
1. set  'Content-Type': "application/json" and "Accept": "application/json" as headers
2. add a json data

**Expected behavior**
Getting a 400 status

**Screenshots**
![image](https://user-images.githubusercontent.com/65462188/110352693-80a7c500-8036-11eb-9751-540799875999.png)
The first status code is from aiohttp with the same headers and json, the second one is from aiosonic using the same headers and json

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser kk
 - Version kk

**Additional context**
nothing.

**Comment by rei-sys** [comment]
Tested on both Windows and Linux

**Comment by sonic182** [comment]
Hi! two questins

can you provide minimal sample code?
did you check which headers are being obtained in your target server?

Best,
Johanderson

**Comment by sonic182** [comment]
Ping @rei-sys

**Comment by sonic182** [comment]
It may be solved in https://github.com/sonic182/aiosonic/issues/235, try with aiosonic 0.9.6
