### ISSUE TITLE
Faster HTTP/2 with libnghttp2 (and easy)

### ISSUE THREAD

**Issue by gatopeich** [sonic182/aiosonic#284]
h2 in my experience is terribly slow.

I had much more success with not-so-well known "pynghttp2" which is a ctypes wrapper around the most popular http/2 library in C.
That would be low hanging fruit.

Also you may want to try libh2o, a potentially faster lib.

**Comment by sonic182** [comment]
For now, I think it's ok to have this client with pure python code, so it works for most python versions >=3.6. People still may prefer this client instead of others just because it's an async client only, not mixed with more stuffs
