### ISSUE TITLE
An open stream object is being garbage collected; call "stream.close()" explicitly

### ISSUE THREAD

**Issue by gatopeich** [sonic182/aiosonic#287]
**Describe the bug**

Using the following code to test connection ton InfluxDB:
```
import asyncio
import aiosonic

async def aiosonic_test():
    c = aiosonic.HTTPClient()
    async def get(url):
        r = await c.get(url)
        print(r.status_code, r.headers, await r.text())

    await get("http://127.0.0.1:8086/ping")
    await get("http://127.0.0.1:8086/query?q=SHOW%20DATABASES")

    await c.wait_requests()
    await c.shutdown()

asyncio.run(aiosonic_test())
```
Works fine but I get an error that the stream was not closed.

**An open stream object is being garbage collected; call "stream.close()" explicitly**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5

**Comment by sonic182** [comment]
Mmm that's weird, can you tell the python version please?

**Comment by gatopeich** [comment]
Python 3.8 and this was inside a Jupyter Noteboon

**Comment by sonic182** [comment]
A bit later but... it still happens?
