### ISSUE TITLE
aiosonic is NOT 288.36% faster than aiohttp

### ISSUE THREAD

**Issue by gatopeich** [sonic182/aiosonic#288]
Running aiosonic performance tests shows only a 20% speed increase over aiohttp which is certainly not as advertised.

https://replit.com/@gatopeich1/isaiosonicreallyfaster#main.py

The results are much closer when reducing concurrency, and the test is very limited just doing a GET / against a local server.

It is really testing "which library is more aggressive about opening new connections" 🙂

**Comment by SomePr0grammer** [comment]
it is faster to an extent though

**Comment by sonic182** [comment]
Docs updated
