### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Gowixx** [sonic182/aiosonic#299]
**Is your feature request related to a problem? Please describe.**
No, It is just a suggestion.

**Describe the solution you'd like**
I want proxy support for the project.

**Describe alternatives you've considered**
Alternatives, such as httpx, already have this. 

**Additional context**
N/A

**Comment by RithDev** [comment]
+1 Would also like it added, even though it wouldn't be hard to implement our self's it'd just be nice to just install aiosonic with proxy support itself.

**Comment by sonic182** [comment]
I knew I would have to do it one day, gonna find some time to do it... To re-read https://datatracker.ietf.org/doc/html/rfc7231

**Comment by RithDev** [comment]
Sounds great!

**Comment by uenro** [comment]
+1 Would also like it added, http will be enough for first time. support of socks proxies is also welcomed!

**Comment by Gowixx** [comment]
^^ Also, any update?

**Comment by sonic182** [comment]
@Gowixx gonna try this week! :smile:

**Comment by Gowixx** [comment]
Okay, Thanks

**Comment by sonic182** [comment]
Basic Proxy support in https://github.com/sonic182/aiosonic/pull/304 (merging it... doing release 0.14.0)

**Comment by Gowixx** [comment]
That was fast, thanks a lot :)

**Comment by sonic182** [comment]
> That was fast, thanks a lot :)

![image](https://user-images.githubusercontent.com/4070466/144006106-3adfa908-b01b-493b-b2a4-fbebcc1c828a.png)

**Comment by Gowixx** [comment]
XD
