### ISSUE TITLE
wait_free_pool loops forever without awaiting?

### ISSUE THREAD

**Issue by ediphy-dwild** [sonic182/aiosonic#332]
**Describe the bug**
We saw ConnectionPoolTimeouts in prod and did a code review of the relevant code, and found something unusual - covered by a pragma

**To Reproduce**
n/a - was a review of code

**Expected behavior**
The wait_free_pool coroutine does not hot loop forever without awaiting

**Screenshots**
![image](https://user-images.githubusercontent.com/26487242/158791765-d35f25a7-6e6d-436e-9bda-89d9e9d54d03.png)

**Desktop (please complete the following information):**
 - linux

**Smartphone (please complete the following information):**
n/a

**Additional context**
It seems to me that if the pool is ever full, this coroutine will loop forever, and the system will never schedule another coroutine. its early so maybe im in space.

**Comment by ediphy-dwild** [comment]
also - any reason to not use an asyncio.condition here to avoid spinning? it seems that even if we await here, then with a large number of connections open the system will have many tasks hosting a coro that sleeps for 20ms each until there is a free slot in the pool

**Comment by sonic182** [comment]
That function is not mean to be used directly, instead to be used by this other function

https://github.com/sonic182/aiosonic/blob/f712a4ba61bc3978550360144f59f3a1a603eefd/aiosonic/__init__.py#L819

**Comment by ediphy-dwild** [comment]
but when its called (by anyone), wont it monopolise the ioloop forever (ie, there is no way out, ever)?

also on further inspection - i think the is_all_free() and free_conns() implementations count whether connections are used rather than free (qsize shows how many items are taken in the queue, rather than free in the queue)

**Comment by sonic182** [comment]
By the time someone call that method, that system should not start any new request with the client instance, if not, it will not finish until the client get's all pool connections free.

For example, If you're in a startlette server, you would want to use `await client.wait_requests()` in the app `on_shutdown` callback

I you only use the HTTPClient class, you should not have any of the problems you describe. But please, feel free to open a PR with your refactor proposal :+1:
