### ISSUE TITLE
RuntimeError: no running event loop

### ISSUE THREAD

**Issue by FF-TeaDoc** [sonic182/aiosonic#338]
**Describe the bug**
When im trying create a aiosonic.HTTPClient() class, i getting a error from asyncio "RuntimeError: no running event loop"

**To Reproduce**
Get Python  3.10.4 version and run code with:
`import aiosonic`
`aiosonic.HTTPClient()`

**Screenshots**
[Screenshot 1](https://prnt.sc/cTqRjij9E4DZ)
[Screenshot 2](https://prnt.sc/vymN1WINqtI9)

**Desktop:**
 - OS: [Windows 10, x64, 21H2]
 - Aiosonic Version: [0.14.0]

**Comment by sonic182** [comment]
I can make the client to obtain the loop when it does calls, but for now, you can just initialize the class inside a coroutine, I mean, with a running loop

**Comment by FF-TeaDoc** [comment]
Ok, it's works. Thank you! But i got an other error. Im gonna close this issue, and open other.
