### ISSUE TITLE
KeyError: 'content_type'

### ISSUE THREAD

**Issue by FF-TeaDoc** [sonic182/aiosonic#339]
When im trying send request on Epic Games service (https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{account_id}/client/FortRerollDailyQuest?profileId=campaign&rvn=-1), im getting error "KeyError: 'content-type'".

**Screenshots**
[await mcp.FortRerollDailyQuest func](https://user-images.githubusercontent.com/78100130/166164047-1ac4412b-68bd-4cdf-abe3-a600decf9122.png)
[self.url](https://user-images.githubusercontent.com/78100130/166164070-4551040c-36cf-41d3-a1f9-42718cc878f0.png)
[Full traceback](https://user-images.githubusercontent.com/78100130/166163955-0a7075e6-c98c-4c48-9fdb-f4c757410f73.png)

**Comment by sonic182** [comment]
Ok I have to do a different kind of exception raising there...

That means that the response was not json, do response.text() instead to check what you got

**Comment by FF-TeaDoc** [comment]
Nonono, This request MUST response a json.

And when im tryed print text, it returns me None.

**Comment by FF-TeaDoc** [comment]
https://github.com/MixV2/EpicResearch/blob/master/docs/mcp/profile/operations/FortRerollDailyQuest.md
https://github.com/MixV2/EpicResearch/blob/master/docs/mcp/profile/operation_request.md

**Comment by FF-TeaDoc** [comment]
Any ideas?

**Comment by FF-TeaDoc** [comment]
![image](https://user-images.githubusercontent.com/78100130/166623190-ee9f5bda-f41f-4751-a6b9-c86e6bc54812.png)

**Comment by FF-TeaDoc** [comment]
Note: I do the same request with modules requests & aiohttp, and this modules don't throws me errors and server responsed me a json. I can't figure out what the problem is...

**Comment by FF-TeaDoc** [comment]
Im only now noticed.

**Comment by FF-TeaDoc** [comment]
Im only now noticed. Look at -1questId. there must be another &. 

DEBUG:aiosonic:POST /fortnite/api/game/v2/profile/eef8ab3555dd4caf91044eb15fc25266/client/FortRerollDailyQuest?profileId=campaign&rvn=-1questId=46c098e0-49f4-458b-926b-67de8c0812c5

And now issue just got fixed cause I pushed all request parameters into params.
