### ISSUE TITLE
Error:  ssl NPN is deprecated, use ALPN instead

### ISSUE THREAD

**Issue by Pablo2m** [sonic182/aiosonic#363]
Python version:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32

Mensagge:
aiosonic\connection.py:110: DeprecationWarning: ssl NPN is deprecated, use ALPN instead
  negotiated_protocol = tls_conn.selected_npn_protocol()

**Comment by sonic182** [comment]
If you see the code, it does:

```python
        # Always prefer the result from ALPN to that from NPN.
        negotiated_protocol = tls_conn.selected_alpn_protocol()
        if negotiated_protocol is None:
            negotiated_protocol = tls_conn.selected_npn_protocol()
```

Where it will prefer ALPN all the time over npn, unless there is no ALPN response
