### ISSUE TITLE
Is there no auth parameter in the get or post methods?

### ISSUE THREAD

**Issue by phenilb** [sonic182/aiosonic#381]
This seems like a great library for python but I am unable to find in the docs about authenticating a HTTPclient for either get or post. There is an auth param in the Proxy class but none in the HTTPclient class itself! 

Help would be greatly appreciated! Thank you!!

**Comment by sonic182** [comment]
You mean basic auth or similar?

It is as simple as follow:

```python
import base64

auth_data = base64.b64encode(b'user:password')

headers = {"Authorization": b"Basic " + auth_data}
```

as explained in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

I don't think it is necessary at the http client, maybe if this issue gets some votes 👍
