### ISSUE TITLE
pip install fails in python3.11

### ISSUE THREAD

**Issue by aithusaqr** [sonic182/aiosonic#410]
There is a problem building the wheel for onecache==0.51 in Python 3.11. When I pip install aiosonic in my venv with python3.11 I get this error:

Building wheels for collected packages: onecache
  Building wheel for onecache (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /private/var/folders/vc/_nb0skyd1y99_st51_2xqvvm0000gn/T/pip-install-u6evf5hl/onecache_342b75d5c1fb49028c2d6b7ee886c42c/setup.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_requirements
      /Users/aisha/PycharmProjects/ohlc/venv/lib/python3.11/site-packages/setuptools/dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/onecache
      copying onecache/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/onecache
      copying onecache/utils.py -> build/lib.macosx-10.9-universal2-cpython-311/onecache
      copying onecache/cache_value.py -> build/lib.macosx-10.9-universal2-cpython-311/onecache
      running build_ext
      building 'onecache.cache_value' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/onecache
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/aisha/PycharmProjects/ohlc/venv/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c onecache/cache_value.c -o build/temp.macosx-10.9-universal2-cpython-311/onecache/cache_value.o
      onecache/cache_value.c:5187:5: error: incomplete definition of type 'struct _frame'
          __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      onecache/cache_value.c:444:62: note: expanded from macro '__Pyx_PyFrame_SetLineNumber'
        #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
                                                            ~~~~~~~^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of 'struct _frame'
      typedef struct _frame PyFrameObject;
                     ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onecache
  Running setup.py clean for onecache
Failed to build onecache
ERROR: Could not build wheels for onecache, which is required to install pyproject.toml-based projects

**Comment by sonic182** [comment]
I have to remove all cython stuff, or just build precompiled versions for onecache package...
