### ISSUE TITLE
HTTPClient context manager gets stuck on exit

### ISSUE THREAD

**Issue by vzakaznikov** [sonic182/aiosonic#448]
**Describe the bug**

The `HTTPClient` context manager gets stuck on exit if the response content is not read or the response connection is not released manually.

**To Reproduce**
```python
async with aiosonic.HTTPClient() as client:
    resp = await client.get('https://github.com')
```

**Expected behavior**
Response connection should be released automatically.

**Workaround**
```python
async with aiosonic.HTTPClient() as client:
    resp = await client.get('https://github.com')
    # either read the response until the end
    print(await resp.content()) 
    # or manually release the response connection
    await resp.connection.release()
```

**Comment by geraldog** [comment]
I confirm the issue exists. Together with #456 you could call an explicit delete on the response within the HTTPClient managed context if you know you're not going to read the response, and it should release the connection thus unblocking Connector cleanup.

Like this:

```
async def main():
    async with aiosonic.HTTPClient() as client:
        resp = await client.get('https://github.com')
        del resp
```
