### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by luwqz1** [sonic182/aiosonic#493]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have class **Formdata** with which it would be possible to create _multipart/form-data_ and send files

**Describe alternatives you've considered**
Formdata is in aiohttp [source code](https://docs.aiohttp.org/en/v3.8.0/_modules/aiohttp/formdata.html)

**Comment by sonic182** [comment]
Have you tried?

```python

    # ##################
    # Post data as multipart form
    # ##################
    url = "https://postman-echo.com/post"
    posted_data = {'foo': 'bar'}
    response = await client.post(url, data=posted_data)
 ```

**Comment by sonic182** [comment]
Seems reasonable, to have a intermediate class that will hold the references to form fields, and then, to stream the form data efficiently

**Comment by luwqz1** [comment]
> Seems reasonable, to have a intermediate class that will hold the references to form fields, and then, to stream the form data efficiently

Can you please provide an example?

**Comment by sonic182** [comment]
> > Seems reasonable, to have a intermediate class that will hold the references to form fields, and then, to stream the form data efficiently
> 
> Can you please provide an example?

Sorry for the delay

Seeing my code, seems that I already did it.

```
@pytest.mark.asyncio
async def test_post_multipart_to_django(live_server):
    """Test post multipart."""
    url = live_server.url + "/post_file"
    data = {"foo": open("tests/files/bar.txt", "rb"), "field1": "foo"}

    async with aiosonic.HTTPClient() as client:
        res = await client.post(url, data=data, multipart=True)
        assert res.status_code == 200
        assert await res.text() == "bar-foo"
```

basically using the `open()` method

**Comment by sonic182** [comment]
New MultipartForm class https://aiosonic.readthedocs.io/en/latest/reference.html#multipart-form-data
